format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$line_break\
$jobs\
[❯](fg:150)[❯](fg:153)[❯](fg:159) """

[directory]
style = "fg:75 bold"
truncation_length = 99
truncate_to_repo = false
read_only = ' \[RO\]'
read_only_style = "fg:75 bold"

[git_branch]
format = "[$branch]($style) "
style = "green"

[git_state]
format = '\([$state ($progress_current/$progress_total)]($style)\) '
rebase = "rebase"
merge = "merge"
revert = "revert"
cherry_pick = "cpick"
bisect = "bisect"
am = "am"
am_or_rebase = "am/rebase"

[git_status]
style = "cyan"

[jobs]
symbol = "+ "
