[hints]
alphabet = "asdfghjkl;"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
# The last 5 characters that are excluded from URL letters are my 'listchars' settings in Vim/Neovim.
regex = "(https:|http:|file:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`\u00AC\u25B8\u00B7\u00BB\u00AB]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Key1"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Key2"
mods = "Control"

[font.normal]
family = "monospace"
